import type { Metadata } from "next";
import { Urbanist, Work_Sans } from "next/font/google";
import "./globals.css";

const urbanist_font = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  fallback: ["system-ui", "Arial", "sans-serif"],
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  fallback: ["system-ui", "Arial", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist_font.variable} ${workSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
